
(() => {
"use strict";
const D=window.NL_DOMESTIC_DATA;if(!D){document.body.innerHTML="<pre>02T domestic data.js could not be loaded.</pre>";return}
const PHYSICAL=D.physical_edges.features||[],DISPLAY=D.display_shapes.features||[],STATIONS=D.stations.features||[],SERVICES=D.service_links||[],TRANSFERS=D.transfers||[],PROVINCES=D.provinces;
const STORE="nl_domestic_progress_v1",LANG_STORE="nl_domestic_lang_v1";
const T={
nl:{title:"Nederland Spoor Compleet",subtitle:"Persoonlijke spoorbereisingskaart",journey:"Reis invoeren",from:"Van",to:"Naar",viaPlaceholder:"Via station...",addVia:"Via toevoegen",addMapWaypoint:"Punt op kaart",clickMapForWaypoint:"Klik op de kaart. Het punt wordt aan het dichtstbijzijnde spoor gekoppeld en kan daarna worden versleept.",preview:"Route tonen",saveJourney:"Reis opslaan",clearSelection:"Selectie wissen",stationClickTip:"Klik op twee stations op de kaart om vertrek en bestemming te kiezen.",visualizeProgress:"Voortgang visualiseren",progressType:"Type",national:"Nederland",province:"Provincie",operator:"Vervoerder",mode:"Vervoerswijze",selection:"Selectie",provinces:"Provincies",operators:"Vervoerders",modes:"Modi",export:"Exporteren",exportMap:"Kaart als PNG exporteren",exportMapNote:"De PNG bevat de geselecteerde voortgang en voortgangsbalk. Alleen NS-stations worden als punten getoond; watervlakken krijgen een blauwe achtergrond.",exportProgress:"Voortgang JSON",importProgress:"JSON importeren",legend:"Legenda",reset:"Alle voortgang wissen",notRidden:"Niet bereisd",routeReady:"Route klaar",routeNotFound:"Geen route gevonden met deze tussenpunten.",chooseBoth:"Kies vertrek- en bestemmingsstation.",saved:"Reis opgeslagen.",resetConfirm:"Alle opgeslagen voortgang wissen?",invalidImport:"Ongeldig voortgangsbestand.",imported:"Voortgang geïmporteerd.",km:"km",selectedScope:"Geselecteerde voortgang",via:"Via",forcedEdge:"Geforceerd spoorpunt",remove:"Verwijder",rail:"Trein",subway:"Metro",tram:"Tram"},
ja:{title:"オランダ鉄道完乗マップ",subtitle:"個人用・鉄道乗車記録",journey:"乗車区間を入力",from:"出発駅",to:"到着駅",viaPlaceholder:"経由駅...",addVia:"経由駅を追加",addMapWaypoint:"地図上に経由点",clickMapForWaypoint:"地図をクリックしてください。最寄りの線路にスナップし、その後ドラッグして調整できます。",preview:"経路を表示",saveJourney:"この経路を乗車済みにする",clearSelection:"選択を解除",stationClickTip:"地図上の駅を2つクリックして出発駅と到着駅を選択できます。",visualizeProgress:"進捗表示",progressType:"表示単位",national:"オランダ全国",province:"州",operator:"運行事業者",mode:"交通モード",selection:"選択",provinces:"州別",operators:"事業者別",modes:"モード別",export:"エクスポート",exportMap:"地図をPNGで保存",exportMapNote:"PNGには選択した範囲の進捗と進捗バーを表示します。",exportProgress:"進捗JSON",importProgress:"JSONを読み込む",legend:"凡例",reset:"進捗をすべて消去",notRidden:"未乗車",routeReady:"経路を表示しました",routeNotFound:"指定した経由点を通る経路を見つけられませんでした。",chooseBoth:"出発駅と到着駅を選んでください。",saved:"乗車記録を保存しました。",resetConfirm:"保存済みの進捗をすべて削除しますか？",invalidImport:"進捗ファイルが正しくありません。",imported:"進捗を読み込みました。",km:"km",selectedScope:"選択した進捗",via:"経由",forcedEdge:"線路経由点",remove:"削除",rail:"鉄道",subway:"地下鉄",tram:"トラム"},
zh:{title:"荷兰铁路完乘地图",subtitle:"个人铁路乘车记录",journey:"输入乘车区间",from:"出发站",to:"到达站",viaPlaceholder:"途经车站...",addVia:"添加途经站",addMapWaypoint:"添加地图途经点",clickMapForWaypoint:"请点击地图。途经点会吸附到最近铁路，并可继续拖动调整。",preview:"显示路线",saveJourney:"将该路线标记为已乘坐",clearSelection:"清除选择",stationClickTip:"可直接在地图上点击两个车站选择出发站和到达站。",visualizeProgress:"进度显示",progressType:"显示类型",national:"荷兰全国",province:"省",operator:"运营商",mode:"交通模式",selection:"选择",provinces:"按省",operators:"按运营商",modes:"按模式",export:"导出",exportMap:"导出地图 PNG",exportMapNote:"PNG 将显示所选范围的进度及进度条。",exportProgress:"导出进度 JSON",importProgress:"导入 JSON",legend:"图例",reset:"清除全部进度",notRidden:"未乘坐",routeReady:"路线已生成",routeNotFound:"无法找到经过这些途经点的路线。",chooseBoth:"请选择出发站和到达站。",saved:"乘车记录已保存。",resetConfirm:"确定清除全部已保存进度吗？",invalidImport:"进度文件无效。",imported:"已导入进度。",km:"km",selectedScope:"所选进度",via:"途经",forcedEdge:"铁路途经点",remove:"删除",rail:"铁路",subway:"地铁",tram:"有轨电车"}};
const COLORS=["#0057a8","#d86f00","#21864a","#8c3a91","#ae3d3d","#5178ba","#857400","#00898a","#ad5d7d","#56616c","#718d28","#936128","#455fc4","#8529a1","#389648","#d87938"];
function splitPipe(v){if(v==null)return[];return[...new Set(String(v).split("|").map(x=>x.trim()).filter(Boolean))]}function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;")}
let lang=localStorage.getItem(LANG_STORE)||"nl";if(!T[lang])lang="nl";function tr(k){return T[lang][k]||T.nl[k]||k}function fmt(v,d=1){return Number(v||0).toLocaleString(lang==="ja"?"ja-JP":lang==="zh"?"zh-CN":"nl-NL",{minimumFractionDigits:d,maximumFractionDigits:d})}
const physicalById=new Map(PHYSICAL.map(f=>[String(f.properties.physical_id),f])),stationById=new Map(),stationByName=new Map();STATIONS.forEach(f=>{const id=String(f.properties.station_id);stationById.set(id,f);stationByName.set(String(f.properties.station_name||"").toLowerCase(),f)});
const operators=[...new Set(PHYSICAL.flatMap(f=>splitPipe(f.properties.operators)))].sort((a,b)=>a.localeCompare(b)),modes=[...new Set(PHYSICAL.flatMap(f=>splitPipe(f.properties.modes)))].sort(),opColor={};operators.forEach((x,i)=>opColor[x]=COLORS[i%COLORS.length]);const primaryOperator=f=>splitPipe(f.properties.operators)[0]||"";
const state={ridden:new Set(),from:null,to:null,constraints:[],previewPhysicalIds:[],addingMapWaypoint:false,activeTab:"province"};try{const x=JSON.parse(localStorage.getItem(STORE)||"[]");if(Array.isArray(x))state.ridden=new Set(x.map(String))}catch{}const saveProgress=()=>localStorage.setItem(STORE,JSON.stringify([...state.ridden]));

// logical service graph
const adjacency=new Map();function addAdj(a,b,e){a=String(a);b=String(b);if(!adjacency.has(a))adjacency.set(a,[]);adjacency.get(a).push({to:b,...e})}
SERVICES.forEach(s=>{const e={cost:Number(s.routing_cost_m||0),physicalIds:splitPipe(s.physical_ids)};addAdj(s.station_a,s.station_b,e);addAdj(s.station_b,s.station_a,e)});TRANSFERS.forEach(t=>{const e={cost:Number(t.routing_cost_m||0),physicalIds:[]};addAdj(t.station_a,t.station_b,e);addAdj(t.station_b,t.station_a,e)});
class Heap{constructor(){this.a=[]}push(x){const a=this.a;a.push(x);let i=a.length-1;while(i>0){const p=(i-1)>>1;if(a[p][0]<=x[0])break;a[i]=a[p];i=p}a[i]=x}pop(){const a=this.a;if(!a.length)return null;const root=a[0],last=a.pop();if(a.length){let i=0;while(true){const l=2*i+1,r=l+1;let c=-1;if(l<a.length)c=l;if(r<a.length&&(c<0||a[r][0]<a[c][0]))c=r;if(c<0||a[c][0]>=last[0])break;a[i]=a[c];i=c}a[i]=last}return root}get size(){return this.a.length}}
const routeCache=new Map();
function routeBetween(a,b){a=String(a);b=String(b);if(a===b)return{cost:0,physicalIds:[]};const key=a<b?`${a}|||${b}`:`${b}|||${a}`;if(routeCache.has(key))return routeCache.get(key);const dist=new Map([[a,0]]),prev=new Map(),heap=new Heap();heap.push([0,a]);while(heap.size){const [d,u]=heap.pop();if(d!==dist.get(u))continue;if(u===b)break;for(const e of adjacency.get(u)||[]){const nd=d+e.cost;if(!dist.has(e.to)||nd<dist.get(e.to)){dist.set(e.to,nd);prev.set(e.to,{from:u,edge:e});heap.push([nd,e.to])}}}if(!dist.has(b)){routeCache.set(key,null);return null}const steps=[];let cur=b;while(cur!==a){const p=prev.get(cur);if(!p){routeCache.set(key,null);return null}steps.push(p.edge);cur=p.from}steps.reverse();const ids=[],seen=new Set();steps.forEach(e=>e.physicalIds.forEach(id=>{id=String(id);if(physicalById.has(id)&&!seen.has(id)){seen.add(id);ids.push(id)}}));const result={cost:dist.get(b),physicalIds:ids};routeCache.set(key,result);return result}
function physicalEndpoints(id){const f=physicalById.get(String(id));if(!f)return null;return{a:String(f.properties.station_a),b:String(f.properties.station_b),length:Number(f.properties.length_m||0)}}function concatIds(a,b){const out=[...a],seen=new Set(out);b.forEach(id=>{id=String(id);if(!seen.has(id)){seen.add(id);out.push(id)}});return out}
function routeWithConstraints(from,constraints,to){let states=new Map([[String(from),{cost:0,physicalIds:[]}]]);
for(const c of constraints){if(c.type==="station"){const target=String(c.stationId);let best=null;states.forEach((s,current)=>{const leg=routeBetween(current,target);if(!leg)return;const x={cost:s.cost+leg.cost,physicalIds:concatIds(s.physicalIds,leg.physicalIds)};if(!best||x.cost<best.cost)best=x});if(!best)return null;states=new Map([[target,best]])}
else{const ep=physicalEndpoints(c.physicalId);if(!ep)return null;const next=new Map();states.forEach((s,current)=>{for(const [entry,exit] of [[ep.a,ep.b],[ep.b,ep.a]]){const leg=routeBetween(current,entry);if(!leg)continue;const x={cost:s.cost+leg.cost+ep.length,physicalIds:concatIds(concatIds(s.physicalIds,leg.physicalIds),[c.physicalId])},old=next.get(exit);if(!old||x.cost<old.cost)next.set(exit,x)}});if(!next.size)return null;states=next}}
let best=null;states.forEach((s,current)=>{const leg=routeBetween(current,String(to));if(!leg)return;const x={cost:s.cost+leg.cost,physicalIds:concatIds(s.physicalIds,leg.physicalIds)};if(!best||x.cost<best.cost)best=x});return best}

// map
const map=L.map("map",{preferCanvas:true,zoomControl:true}).setView([52.1,5.4],8);if(D.frontend_settings?.use_carto_basemap)L.tileLayer("https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png",{subdomains:"abcd",maxZoom:19,attribution:"&copy; OpenStreetMap contributors &copy; CARTO",className:"carto-tiles"}).addTo(map);
const renderer=L.canvas({padding:.5}),provinceLayer=L.geoJSON(PROVINCES,{interactive:false,style:{color:"#bcbcb6",weight:1,fillColor:"#f7f7f4",fillOpacity:.08}}).addTo(map);provinceLayer.eachLayer(l=>{try{const name=l.feature.properties.province||"",c=l.getBounds().getCenter();L.marker(c,{interactive:false,icon:L.divIcon({className:"",html:`<div class="province-name">${esc(name)}</div>`,iconSize:[100,18],iconAnchor:[50,9]})}).addTo(map)}catch{}});
L.geoJSON(D.display_shapes,{renderer,interactive:false,style:{color:"#bdbdb8",weight:1.25,opacity:.44,lineCap:"round",lineJoin:"round"}}).addTo(map);

function provinceLength(f,p){try{const raw=f.properties.province_lengths_m,o=typeof raw==="string"?JSON.parse(raw):raw||{};return Number(o[p]||0)}catch{return 0}}
function scopeWeight(f){const type=document.getElementById("scope-type").value,item=document.getElementById("scope-item").value,L=Number(f.properties.length_m||0);if(type==="national")return L;if(type==="province")return provinceLength(f,item);if(type==="operator")return splitPipe(f.properties.operators).includes(item)?L:0;if(type==="mode")return splitPipe(f.properties.modes).includes(item)?L:0;return L}
const physicalLayers=new Map();function physicalStyle(f){const ridden=state.ridden.has(String(f.properties.physical_id)),active=scopeWeight(f)>0;if(ridden)return{color:opColor[primaryOperator(f)]||"#20201f",weight:active?5.8:3.6,opacity:active?.98:.28,lineCap:"round",lineJoin:"round"};return{color:active?"#888884":"#c7c7c2",weight:active?2.25:1,opacity:active?.72:.22,lineCap:"round",lineJoin:"round"}}
L.geoJSON(D.physical_edges,{renderer,interactive:false,style:physicalStyle,onEachFeature:(f,l)=>physicalLayers.set(String(f.properties.physical_id),l)}).addTo(map);
const previewLayer=L.geoJSON({type:"FeatureCollection",features:[]},{renderer,interactive:false,style:{color:"#171716",weight:7,opacity:.9,dashArray:"10 7",lineCap:"round"}}).addTo(map);

// stations
const stationMarkers=new Map();function stationName(id){return stationById.get(String(id))?.properties?.station_name||""}function stationIcon(id){let cls="station-dot";if(state.from===id)cls+=" from";if(state.to===id)cls+=" to";if(state.constraints.some(c=>c.type==="station"&&c.stationId===id))cls+=" via";return L.divIcon({className:"",html:`<div class="${cls}"></div>`,iconSize:[14,14],iconAnchor:[7,7]})}function activeOperator(){const type=document.getElementById("scope-type").value;if(type!=="operator")return null;return document.getElementById("scope-item").value||null}
function stationVisibleForCurrentScope(f){const op=activeOperator();if(!op)return true;return splitPipe(f.properties.operators).includes(op)}function nsStationForExport(f){const ops=splitPipe(f?.properties?.operators).map(x=>String(x).trim().toLowerCase());return ops.includes("ns")||ops.includes("nederlandse spoorwegen")||ops.includes("nederlandse spoorwegen nv")}
function rebuildStationDatalist(){const list=document.getElementById("stations-list");list.innerHTML="";STATIONS.filter(stationVisibleForCurrentScope).sort((a,b)=>String(a.properties.station_name).localeCompare(String(b.properties.station_name))).forEach(f=>{const o=document.createElement("option");o.value=f.properties.station_name;list.appendChild(o)})}
function refreshStationIcons(){stationMarkers.forEach((m,id)=>{m.setIcon(stationIcon(id));const f=stationById.get(String(id));const visible=f?stationVisibleForCurrentScope(f):false;if(visible){if(!map.hasLayer(m))m.addTo(map)}else{if(map.hasLayer(m))map.removeLayer(m)}});rebuildStationDatalist()}
STATIONS.forEach(f=>{const id=String(f.properties.station_id),[lon,lat]=f.geometry.coordinates,m=L.marker([lat,lon],{icon:stationIcon(id),riseOnHover:true,bubblingMouseEvents:false});m.bindTooltip(esc(f.properties.station_name),{direction:"top",offset:[0,-5],className:"station-tip"});m.on("click",()=>{if(state.addingMapWaypoint)return;if(state.from===null||(state.from!==null&&state.to!==null)){state.from=id;state.to=null}else if(id!==state.from)state.to=id;syncInputs();refreshStationIcons();clearPreview();if(state.from&&state.to)previewRoute()});m.addTo(map);stationMarkers.set(id,m)});
function stationFromInput(text){const q=String(text||"").trim().toLowerCase();if(!q)return null;const candidates=STATIONS.filter(stationVisibleForCurrentScope);const exact=candidates.find(x=>String(x.properties.station_name||"").toLowerCase()===q);if(exact)return String(exact.properties.station_id);const f=candidates.find(x=>String(x.properties.station_name||"").toLowerCase().includes(q));return f?String(f.properties.station_id):null}
function syncInputs(){document.getElementById("from-input").value=state.from?stationName(state.from):"";document.getElementById("to-input").value=state.to?stationName(state.to):""}function syncStateFromInputs(){state.from=stationFromInput(document.getElementById("from-input").value);state.to=stationFromInput(document.getElementById("to-input").value);refreshStationIcons()}
function addViaStation(){const input=document.getElementById("via-input"),sid=stationFromInput(input.value);if(!sid)return;state.constraints.push({type:"station",stationId:sid});input.value="";refreshConstraints();refreshStationIcons();clearPreview()}

// map waypoints
function metersXY(lon,lat){const lat0=52.15*Math.PI/180;return[lon*111320*Math.cos(lat0),lat*110540]}function nearestOnSegment(px,py,ax,ay,bx,by){const vx=bx-ax,vy=by-ay,wx=px-ax,wy=py-ay,vv=vx*vx+vy*vy;let t=vv>0?(wx*vx+wy*vy)/vv:0;t=Math.max(0,Math.min(1,t));const x=ax+t*vx,y=ay+t*vy,dx=px-x,dy=py-y;return{d2:dx*dx+dy*dy,t}}
const edgeSearch=PHYSICAL.map(f=>{const parts=f.geometry.type==="LineString"?[f.geometry.coordinates]:f.geometry.coordinates;let minLon=Infinity,minLat=Infinity,maxLon=-Infinity,maxLat=-Infinity;parts.forEach(line=>line.forEach(([lon,lat])=>{minLon=Math.min(minLon,lon);maxLon=Math.max(maxLon,lon);minLat=Math.min(minLat,lat);maxLat=Math.max(maxLat,lat)}));return{id:String(f.properties.physical_id),parts,minLon,maxLon,minLat,maxLat}});
function snapNearest(lat,lon){const[px,py]=metersXY(lon,lat),pad=.12;let best=null,candidates=edgeSearch.filter(e=>lon>=e.minLon-pad&&lon<=e.maxLon+pad&&lat>=e.minLat-pad&&lat<=e.maxLat+pad);if(!candidates.length)candidates=edgeSearch;candidates.forEach(e=>e.parts.forEach(line=>{for(let i=0;i<line.length-1;i++){const[lon1,lat1]=line[i],[lon2,lat2]=line[i+1],[ax,ay]=metersXY(lon1,lat1),[bx,by]=metersXY(lon2,lat2),q=nearestOnSegment(px,py,ax,ay,bx,by);if(!best||q.d2<best.d2)best={physicalId:e.id,lon:lon1+q.t*(lon2-lon1),lat:lat1+q.t*(lat2-lat1),d2:q.d2}}}));return best}
function waypointIcon(){return L.divIcon({className:"",html:`<div class="edge-waypoint"></div>`,iconSize:[18,18],iconAnchor:[9,9]})}
function addEdgeConstraint(lat,lon){const s=snapNearest(lat,lon);if(!s)return;const c={type:"edge",physicalId:s.physicalId,lat:s.lat,lon:s.lon,marker:null},m=L.marker([s.lat,s.lon],{draggable:true,icon:waypointIcon(),zIndexOffset:1000,bubblingMouseEvents:false}).addTo(map);c.marker=m;m.on("dragend",()=>{const p=m.getLatLng(),x=snapNearest(p.lat,p.lng);if(!x)return;c.physicalId=x.physicalId;c.lat=x.lat;c.lon=x.lon;m.setLatLng([x.lat,x.lon]);refreshConstraints();clearPreview()});state.constraints.push(c);refreshConstraints();clearPreview()}
map.on("click",e=>{if(!state.addingMapWaypoint)return;state.addingMapWaypoint=false;document.getElementById("map-waypoint-help").textContent="";addEdgeConstraint(e.latlng.lat,e.latlng.lng)});

function removeConstraint(i){const c=state.constraints[i];if(c?.type==="edge"&&c.marker)map.removeLayer(c.marker);state.constraints.splice(i,1);refreshConstraints();refreshStationIcons();clearPreview()}
function refreshConstraints(){const box=document.getElementById("constraints");box.innerHTML=state.constraints.map((c,i)=>{let text;if(c.type==="station")text=`${tr("via")}: ${stationName(c.stationId)}`;else{const p=physicalById.get(String(c.physicalId))?.properties;text=`${tr("forcedEdge")}: ${p?`${p.station_a_name} – ${p.station_b_name}`:c.physicalId}`}return`<div class="constraint"><span class="constraint-index">${i+1}.</span><span>${esc(text)}</span><button data-remove="${i}">${tr("remove")}</button></div>`}).join("");box.querySelectorAll("[data-remove]").forEach(b=>b.addEventListener("click",()=>removeConstraint(Number(b.dataset.remove))))}

function clearPreview(){previewLayer.clearLayers();state.previewPhysicalIds=[];document.getElementById("save-route").disabled=true}
function previewRoute(){syncStateFromInputs();const msg=document.getElementById("route-message");if(!state.from||!state.to){msg.textContent=tr("chooseBoth");clearPreview();return}const r=routeWithConstraints(state.from,state.constraints,state.to);if(!r){msg.textContent=tr("routeNotFound");clearPreview();return}state.previewPhysicalIds=r.physicalIds;const fs=r.physicalIds.map(id=>physicalById.get(String(id))).filter(Boolean);previewLayer.clearLayers();previewLayer.addData({type:"FeatureCollection",features:fs});if(fs.length){try{map.fitBounds(previewLayer.getBounds(),{padding:[40,40],maxZoom:12})}catch{}}const d=r.physicalIds.reduce((s,id)=>s+Number(physicalById.get(String(id))?.properties?.length_m||0),0);msg.textContent=`${tr("routeReady")}: ${stationName(state.from)} → ${stationName(state.to)} · ${fmt(d/1000)} ${tr("km")}`;document.getElementById("save-route").disabled=!r.physicalIds.length}
function saveRoute(){if(!state.previewPhysicalIds.length)return;state.previewPhysicalIds.forEach(id=>state.ridden.add(String(id)));saveProgress();document.getElementById("route-message").textContent=tr("saved");state.from=state.to;state.to=null;state.constraints.forEach(c=>{if(c.type==="edge"&&c.marker)map.removeLayer(c.marker)});state.constraints=[];clearPreview();syncInputs();refreshConstraints();refreshStationIcons();refreshAll()}
function clearJourney(){state.from=null;state.to=null;state.constraints.forEach(c=>{if(c.type==="edge"&&c.marker)map.removeLayer(c.marker)});state.constraints=[];clearPreview();syncInputs();refreshConstraints();refreshStationIcons();document.getElementById("route-message").textContent=""}

// progress
const provinces=[...new Set(PHYSICAL.flatMap(f=>{try{const raw=f.properties.province_lengths_m,o=typeof raw==="string"?JSON.parse(raw):raw||{};return Object.keys(o)}catch{return[]}}))].sort((a,b)=>a.localeCompare(b));function displayMode(m){return tr(m)||m}
function scopeTitle(){const type=document.getElementById("scope-type").value,item=document.getElementById("scope-item").value;if(type==="national")return tr("national");if(type==="mode")return displayMode(item);return item||tr(type)}
function populateScopeItems(){const type=document.getElementById("scope-type").value,s=document.getElementById("scope-item"),old=s.value;let values=[],label=x=>x;if(type==="province")values=provinces;else if(type==="operator")values=operators;else if(type==="mode"){values=modes;label=displayMode}s.innerHTML="";if(type==="national"){s.disabled=true;const o=document.createElement("option");o.value="";o.textContent=tr("national");s.appendChild(o)}else{s.disabled=false;values.forEach(v=>{const o=document.createElement("option");o.value=v;o.textContent=label(v);s.appendChild(o)});if(values.includes(old))s.value=old}refreshStationIcons();refreshAll()}
function totalScopeM(){return PHYSICAL.reduce((s,f)=>s+scopeWeight(f),0)}function riddenScopeM(){return PHYSICAL.reduce((s,f)=>s+(state.ridden.has(String(f.properties.physical_id))?scopeWeight(f):0),0)}
function refreshProgressCard(){const total=totalScopeM(),done=riddenScopeM(),pct=total?100*done/total:0;document.getElementById("scope-title").textContent=scopeTitle();document.getElementById("scope-pct").textContent=`${fmt(pct)}%`;document.getElementById("scope-distance").textContent=`${fmt(done/1000)} / ${fmt(total/1000)} ${tr("km")}`;document.getElementById("scope-bar").style.width=`${Math.max(0,Math.min(100,pct))}%`}
function restylePhysical(){PHYSICAL.forEach(f=>{const l=physicalLayers.get(String(f.properties.physical_id));if(l)l.setStyle(physicalStyle(f))})}
function statGroups(kind){const g=new Map();PHYSICAL.forEach(f=>{const p=f.properties;if(kind==="province"){try{const raw=p.province_lengths_m,o=typeof raw==="string"?JSON.parse(raw):raw||{};Object.entries(o).forEach(([k,w])=>{w=Number(w);if(w<=0)return;if(!g.has(k))g.set(k,[]);g.get(k).push({f,w})})}catch{}}else{const keys=kind==="operator"?splitPipe(p.operators):splitPipe(p.modes);keys.forEach(k=>{if(!g.has(k))g.set(k,[]);g.get(k).push({f,w:Number(p.length_m||0)})})}});return g}
function renderStats(){const rows=[];statGroups(state.activeTab).forEach((xs,k)=>{const total=xs.reduce((s,x)=>s+x.w,0),done=xs.reduce((s,x)=>s+(state.ridden.has(String(x.f.properties.physical_id))?x.w:0),0);rows.push({name:state.activeTab==="mode"?displayMode(k):k,total,done,pct:total?100*done/total:0})});rows.sort((a,b)=>b.total-a.total);document.getElementById("stats").innerHTML=rows.map(r=>`<div class="stat"><div class="stat-top"><div class="stat-name" title="${esc(r.name)}">${esc(r.name)}</div><div class="stat-val">${fmt(r.pct)}% · ${fmt(r.done/1000)}/${fmt(r.total/1000)} ${tr("km")}</div></div><div class="bar"><div style="width:${Math.min(100,r.pct)}%"></div></div></div>`).join("")}
function renderLegend(){document.getElementById("legend").innerHTML=operators.map(op=>`<div class="legend-row"><span class="swatch" style="background:${opColor[op]}"></span><span>${esc(op)}</span></div>`).join("")+`<div class="legend-row"><span class="swatch" style="height:3px;background:#92928e"></span><span>${tr("notRidden")}</span></div>`}
function refreshAll(){restylePhysical();refreshProgressCard();renderStats()}

// json import/export
function exportProgress(){const p={schema:"nl_domestic_progress_v1",country_code:"NL",exported_at:new Date().toISOString(),ridden_physical_ids:[...state.ridden]},blob=new Blob([JSON.stringify(p,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="netherlands_rail_progress.json";document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)}
function importProgress(file){const r=new FileReader();r.onload=()=>{try{const p=JSON.parse(r.result);if(p.country_code!=="NL"||!Array.isArray(p.ridden_physical_ids))throw new Error();state.ridden=new Set(p.ridden_physical_ids.map(String).filter(id=>physicalById.has(id)));saveProgress();refreshAll();alert(tr("imported"))}catch{alert(tr("invalidImport"))}};r.readAsText(file)}

// PNG export; vector-only, so tile availability never affects exported image
function mercator(lon,lat){const x=lon*Math.PI/180,c=Math.max(-85,Math.min(85,lat)),y=Math.log(Math.tan(Math.PI/4+c*Math.PI/360));return[x,y]}
function visitGeom(g,fn){if(!g)return;if(g.type==="LineString")fn(g.coordinates,false);else if(g.type==="MultiLineString")g.coordinates.forEach(x=>fn(x,false));else if(g.type==="Polygon")g.coordinates.forEach(x=>fn(x,true));else if(g.type==="MultiPolygon")g.coordinates.forEach(p=>p.forEach(x=>fn(x,true)))}
function exportMapPng(){const W=1800,H=1250,m=90,hh=150,fh=150,c=document.createElement("canvas");c.width=W;c.height=H;const ctx=c.getContext("2d");
ctx.fillStyle="#dfe7ec";ctx.fillRect(0,0,W,H);
const scoped=PHYSICAL.filter(f=>scopeWeight(f)>0),fit=scoped.length?scoped:PHYSICAL;let minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;
fit.forEach(f=>visitGeom(f.geometry,cs=>cs.forEach(([lon,lat])=>{const[x,y]=mercator(lon,lat);minX=Math.min(minX,x);maxX=Math.max(maxX,x);minY=Math.min(minY,y);maxY=Math.max(maxY,y)})));
PROVINCES.features.forEach(f=>visitGeom(f.geometry,cs=>cs.forEach(([lon,lat])=>{const[x,y]=mercator(lon,lat);minX=Math.min(minX,x);maxX=Math.max(maxX,x);minY=Math.min(minY,y);maxY=Math.max(maxY,y)})));
if(!Number.isFinite(minX)){minX=0;minY=0;maxX=1;maxY=1}
const dx=Math.max(1e-9,maxX-minX),dy=Math.max(1e-9,maxY-minY);minX-=dx*.07;maxX+=dx*.07;minY-=dy*.07;maxY+=dy*.07;
const mapX=m,mapY=hh,mapW=W-2*m,mapH=H-hh-fh,scale=Math.min(mapW/(maxX-minX),mapH/(maxY-minY)),usedW=(maxX-minX)*scale,usedH=(maxY-minY)*scale,ox=mapX+(mapW-usedW)/2,oy=mapY+(mapH-usedH)/2;
const P=(lon,lat)=>{const[x,y]=mercator(lon,lat);return[ox+(x-minX)*scale,oy+usedH-(y-minY)*scale]};

ctx.fillStyle="#dfe7ec";ctx.fillRect(mapX,mapY,mapW,mapH);
ctx.fillStyle="#f7f7f4";ctx.strokeStyle="#c8c8c1";ctx.lineWidth=1.3;
PROVINCES.features.forEach(f=>visitGeom(f.geometry,(cs,closed)=>{if(!cs.length)return;ctx.beginPath();cs.forEach(([lon,lat],i)=>{const[x,y]=P(lon,lat);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});if(closed){ctx.closePath();ctx.fill("evenodd")}ctx.stroke()}));

ctx.lineCap="round";ctx.lineJoin="round";ctx.strokeStyle="#c2c2bd";ctx.lineWidth=1;
DISPLAY.forEach(f=>visitGeom(f.geometry,cs=>{if(cs.length<2)return;ctx.beginPath();cs.forEach(([lon,lat],i)=>{const[x,y]=P(lon,lat);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()}));

ctx.strokeStyle="#7f7f7a";ctx.lineWidth=2.1;
scoped.forEach(f=>{if(state.ridden.has(String(f.properties.physical_id)))return;visitGeom(f.geometry,cs=>{ctx.beginPath();cs.forEach(([lon,lat],i)=>{const[x,y]=P(lon,lat);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()})});

scoped.forEach(f=>{if(!state.ridden.has(String(f.properties.physical_id)))return;ctx.strokeStyle=opColor[primaryOperator(f)]||"#20201f";ctx.lineWidth=5.2;visitGeom(f.geometry,cs=>{ctx.beginPath();cs.forEach(([lon,lat],i)=>{const[x,y]=P(lon,lat);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()})});

ctx.fillStyle="#fff";ctx.strokeStyle="#222";ctx.lineWidth=1;
STATIONS.filter(nsStationForExport).forEach(f=>{const[lon,lat]=f.geometry.coordinates,[x,y]=P(lon,lat);if(x<mapX-10||x>mapX+mapW+10||y<mapY-10||y>mapY+mapH+10)return;ctx.beginPath();ctx.arc(x,y,2.4,0,Math.PI*2);ctx.fill();ctx.stroke()});

const total=totalScopeM(),done=riddenScopeM(),pct=total?100*done/total:0;
ctx.fillStyle="#20201f";ctx.textAlign="left";ctx.font="700 42px Arial,sans-serif";ctx.fillText(scopeTitle(),m,58);
ctx.font="700 30px Arial,sans-serif";ctx.fillText(`${fmt(pct)}%`,m,108);
ctx.fillStyle="#666";ctx.font="22px Arial,sans-serif";ctx.fillText(`${fmt(done/1000)} / ${fmt(total/1000)} ${tr("km")}`,m+150,108);

const bx=m,by=H-fh+42,bw=W-2*m,bh=30;
ctx.fillStyle="#deded9";ctx.fillRect(bx,by,bw,bh);
ctx.fillStyle="#20201f";ctx.fillRect(bx,by,bw*Math.max(0,Math.min(1,pct/100)),bh);
ctx.fillStyle="#555";ctx.font="18px Arial,sans-serif";ctx.fillText(`${tr("selectedScope")}: ${scopeTitle()}`,bx,by+66);

c.toBlob(blob=>{if(!blob)return;const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="netherlands_rail_progress.png";document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)},"image/png")}

// language + controls
function updateLanguage(){document.documentElement.lang=lang==="ja"?"ja":lang==="zh"?"zh-CN":"nl";document.title=tr("title");document.querySelectorAll("[data-t]").forEach(el=>{const k=el.dataset.t;if(T[lang][k])el.textContent=T[lang][k]});document.querySelectorAll("[data-t-option]").forEach(el=>{const k=el.dataset.tOption;if(T[lang][k])el.textContent=T[lang][k]});document.querySelectorAll("[data-t-placeholder]").forEach(el=>{const k=el.dataset.tPlaceholder;if(T[lang][k])el.placeholder=T[lang][k]});document.querySelectorAll(".lang").forEach(b=>b.classList.toggle("active",b.dataset.lang===lang));populateScopeItems();refreshConstraints();refreshStationIcons();renderLegend();refreshAll()}
const datalist=document.getElementById("stations-list");rebuildStationDatalist();
function populateScopeItems(){const type=document.getElementById("scope-type").value,s=document.getElementById("scope-item"),old=s.value;let values=[],label=x=>x;if(type==="province")values=provinces;else if(type==="operator")values=operators;else if(type==="mode"){values=modes;label=displayMode}s.innerHTML="";if(type==="national"){s.disabled=true;const o=document.createElement("option");o.value="";o.textContent=tr("national");s.appendChild(o)}else{s.disabled=false;values.forEach(v=>{const o=document.createElement("option");o.value=v;o.textContent=label(v);s.appendChild(o)});if(values.includes(old))s.value=old}refreshStationIcons();refreshAll()}
document.querySelectorAll(".lang").forEach(b=>b.addEventListener("click",()=>{lang=b.dataset.lang;localStorage.setItem(LANG_STORE,lang);updateLanguage()}));document.getElementById("add-via").addEventListener("click",addViaStation);document.getElementById("add-map-waypoint").addEventListener("click",()=>{state.addingMapWaypoint=true;document.getElementById("map-waypoint-help").textContent=tr("clickMapForWaypoint")});document.getElementById("preview-route").addEventListener("click",previewRoute);document.getElementById("save-route").addEventListener("click",saveRoute);document.getElementById("clear-route").addEventListener("click",clearJourney);document.getElementById("from-input").addEventListener("change",()=>{syncStateFromInputs();clearPreview()});document.getElementById("to-input").addEventListener("change",()=>{syncStateFromInputs();clearPreview()});document.getElementById("scope-type").addEventListener("change",populateScopeItems);document.getElementById("scope-item").addEventListener("change",()=>{refreshStationIcons();refreshAll()});document.querySelectorAll(".tab").forEach(b=>b.addEventListener("click",()=>{state.activeTab=b.dataset.tab;document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x===b));renderStats()}));document.getElementById("export-map").addEventListener("click",exportMapPng);document.getElementById("export-progress").addEventListener("click",exportProgress);document.getElementById("import-progress").addEventListener("change",e=>{const f=e.target.files?.[0];if(f)importProgress(f);e.target.value=""});document.getElementById("reset-progress").addEventListener("click",()=>{if(!confirm(tr("resetConfirm")))return;state.ridden.clear();saveProgress();refreshAll()});
try{map.fitBounds(provinceLayer.getBounds(),{padding:[15,15]})}catch{}populateScopeItems();refreshConstraints();renderLegend();updateLanguage();syncInputs();refreshStationIcons();refreshAll();
})();
